apiVersion: v1
kind: Service
metadata:
  name: kryptokrona-service
  namespace: kryptokrona
spec:
  selector:
    app: kryptokrona-service
  ports:
    - port: 8070
      targetPort: 8070
      name: "inbound-to-node"
  type: LoadBalancer